# -*- coding: utf-8 -*-
# This file is the single source of truth for module metadata.
# It is intended to be loaded and queried by the backend services.

MODULE_REGISTRY = {
    "communications": {
        "module_key": "communications",
        "module_name": "Communications Hub",
        "module_family": "Business Operations",
        "description": "Unified inbox and communication tools for customer and team messaging.",
        "surfaces": ["app", "admin"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_communications",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "native",
    },
    "compliance": {
        "module_key": "compliance",
        "module_name": "Compliance Manager",
        "module_family": "Risk & Governance",
        "description": "Tools for managing and monitoring regulatory compliance.",
        "surfaces": ["app", "admin"],
        "visibility_rules": ["requires_professional_plan"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_compliance",
        "onboarding_requirement": True,
        "linked_external_service": None,
        "implementation_type": "native",
    },
    "customers": {
        "module_key": "customers",
        "module_name": "Customer Relationship Management (CRM)",
        "module_family": "Customer Engagement",
        "description": "Core CRM functionality for managing customer data and interactions.",
        "surfaces": ["app", "admin"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_crm",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "native",
    },
    "finance": {
        "module_key": "finance",
        "module_name": "Finance & Accounting",
        "module_family": "Financial Management",
        "description": "Manages invoicing, expenses, and financial reporting.",
        "surfaces": ["app", "admin"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "external_sso",
        "entitlement_requirement": "entitlement_finance",
        "onboarding_requirement": True,
        "linked_external_service": "quickbooks",
        "implementation_type": "external",
    },
    "insights": {
        "module_key": "insights",
        "module_name": "Business Insights",
        "module_family": "Analytics",
        "description": "Provides dashboards and reports on business performance.",
        "surfaces": ["app", "admin"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_insights",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "native",
    },
    "knowledge": {
        "module_key": "knowledge",
        "module_name": "Knowledge Base",
        "module_family": "Business Operations",
        "description": "Internal wiki and knowledge management system.",
        "surfaces": ["app"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_knowledge",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "native",
    },
    "learning": {
        "module_key": "learning",
        "module_name": "Learning Management System (LMS)",
        "module_family": "Team Management",
        "description": "Platform for creating and delivering training courses.",
        "surfaces": ["app"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_learning",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "native",
    },
    "lending": {
        "module_key": "lending",
        "module_name": "Lending Platform",
        "module_family": "Financial Management",
        "description": "Manages loan applications, underwriting, and servicing.",
        "surfaces": ["app", "admin", "portal"],
        "visibility_rules": ["requires_financial_plan"],
        "launch_pattern": "external_sso",
        "entitlement_requirement": "entitlement_lending",
        "onboarding_requirement": True,
        "linked_external_service": "plaid",
        "implementation_type": "external",
    },
    "operations": {
        "module_key": "operations",
        "module_name": "Operations Dashboard",
        "module_family": "Business Operations",
        "description": "Tools for managing day-to-day business operations and workflows.",
        "surfaces": ["app", "admin"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_operations",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "native",
    },
    "people": {
        "module_key": "people",
        "module_name": "Human Resources (HR)",
        "module_family": "Team Management",
        "description": "Manages employee records, payroll, and time off.",
        "surfaces": ["app", "admin"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "external_sso",
        "entitlement_requirement": "entitlement_hr",
        "onboarding_requirement": True,
        "linked_external_service": "gusto",
        "implementation_type": "external",
    },
    "sales": {
        "module_key": "sales",
        "module_name": "Sales Pipeline",
        "module_family": "Customer Engagement",
        "description": "Manages sales leads, deals, and pipeline forecasting.",
        "surfaces": ["app", "admin"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_sales",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "native",
    },
    "support": {
        "module_key": "support",
        "module_name": "Support Ticketing",
        "module_family": "Customer Engagement",
        "description": "Manages customer support requests and tickets.",
        "surfaces": ["app", "admin", "portal"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_support",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "native",

    },
    "teams": {
        "module_key": "teams",
        "module_name": "Team Collaboration",
        "module_family": "Team Management",
        "description": "Tools for team chat, project management, and collaboration.",
        "surfaces": ["app"],
        "visibility_rules": ["requires_active_subscription"],
        "launch_pattern": "internal_route",
        "entitlement_requirement": "entitlement_teams",
        "onboarding_requirement": False,
        "linked_external_service": None,
        "implementation_type": "integration_pending",
    },
}
